#!/bin/bash

TOKEN=""
HBP_ID=""
RUN_INSTR=""

NARGS=$(($#-1))

for (( iarg=1; iarg<=NARGS; iarg++)); do
    jarg=$((iarg+1))

    if [ ${!iarg} == "--token" ]
        then
            TOKEN=${!jarg}
    fi
    if [ ${!iarg} == "--run" ]
        then
            RUN_INSTR=${!jarg}
    fi
    if [ ${!iarg} == "--id" ]
        then
            HBP_ID=${!jarg}
    fi
done

if [ "$HBP_ID" == "" ] || [ "$TOKEN" == "" ]; then
    echo "Parameters are missing:"
    if [ "$HBP_TOKEN" == "" ]; then
        echo "--token: login authentification token string for HBP account"
    fi
    if [ "$HBP_ID" == "" ]; then
        echo "--id: identifier string for of the model in EBRAINS database"
    fi
    if [ "$RUN_INSTR" == "" ]; then
        echo "--run: running instruction string to run the model"
    fi
else
    python3 $( dirname -- "$0"; )/main.py --token $TOKEN --id $HBP_ID --run $RUN_INSTR
fi